export const GET_TODOS_REQUEST = "GET_TODOS_REQUEST"
export const GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS"
export const GET_TODOS_FAILURE = "GET_TODOS_FAILURE"

export const TODO_COMPLETE_REQUEST = "TODO_COMPLETE_REQUEST"
export const TODO_COMPLETE_SUCCESS = "TODO_COMPLETE_SUCCESS"
export const TODO_COMPLETE_FAILURE = "TODO_COMPLETE_FAILURE"

export const ADD_TODO_REQUEST = "ADD_TODO_REQUEST"
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS"
export const ADD_TODO_FAILURE = "ADD_TODO_FAILURE"

export const EDIT_TODO_REQUEST = "EDIT_TODO_REQUEST"
export const EDIT_TODO_SUCCESS = "EDIT_TODO_SUCCESS"
export const EDIT_TODO_FAILURE = "EDIT_TODO_FAILURE"