export const GET_TODOS_REQUEST = "GET_TODOS_REQUEST"
export const GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS"
export const GET_TODOS_FAILURE = "GET_TODOS_FAILURE"

export const TODO_COMPLETE_REQUEST = "TODO_COMPLETE_REQUEST"
export const TODO_COMPLETE_SUCCESS = "TODO_COMPLETE_SUCCESS"
export const TODO_COMPLETE_FAILURE = "TODO_COMPLETE_FAILURE"